db.versions.remove({candidate:'groovy', version:/1.7.[0-9]?/})
db.versions.insert({candidate:"groovy", version:"1.7.0", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.0.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.1", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.1.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.2", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.2.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.3", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.3.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.4", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.4.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.5", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.5.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.6", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.6.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.7", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.7.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.8", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.8.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.9", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.9.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.10", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.10.zip"})
db.versions.insert({candidate:"groovy", version:"1.7.11", url:"http://dist.groovy.codehaus.org/distributions/groovy-binary-1.7.11.zip"})
