db.application.update({_id:1}, {$set: {gvmVersion:"0.8.3"}})
db.candidates.insert({candidate:"vert.x", default:"1.3.0.final"})
db.versions.insert({candidate:"vert.x", version:"1.1.0.final", url:"https://s3.amazonaws.com/vert.x/vert.x-1.1.0.final.zip"})
db.versions.insert({candidate:"vert.x", version:"1.2.0.final", url:"https://s3.amazonaws.com/vert.x/vert.x-1.2.0.final.zip"})
db.versions.insert({candidate:"vert.x", version:"1.2.1.final", url:"https://s3.amazonaws.com/vert.x/vert.x-1.2.1.final.zip"})
db.versions.insert({candidate:"vert.x", version:"1.2.2.final", url:"https://s3.amazonaws.com/vert.x/vert.x-1.2.2.final.zip"})
db.versions.insert({candidate:"vert.x", version:"1.2.3.final", url:"http://vertx.io/downloads/vert.x-1.2.3.final.zip"})
db.versions.insert({candidate:"vert.x", version:"1.3.0.final", url:"http://vertx.io/downloads/vert.x-1.3.0.final.zip"})
db.broadcast.remove()
db.broadcast.insert({ "_id" : 1, "text" : "GVM version 0.8.3 release!" })
db.broadcast.insert({ "_id" : 2, "text" : "New feature:" })
db.broadcast.insert({ "_id" : 3, "text" : " * introduce new candidate: vert.x" })
db.broadcast.insert({ "_id" : 4, "text" : " * use gradle as build system" })
db.broadcast.insert({ "_id" : 5, "text" : " * prebuild archive for install + selfupdate" })
db.broadcast.insert({ "_id" : 6, "text" : " * minor bug fixes" })
db.broadcast.insert({ "_id" : 7, "text" : "" })
db.broadcast.insert({ "_id" : 8, "text" : "As always, please report any issues at:" })
db.broadcast.insert({ "_id" : 9, "text" : " https://github.com/gvmtool/gvm/issues" })


