db.broadcast.remove();
db.broadcast.insert({ "_id": 1, "text": "GVM version 0.9.0                            " });
db.broadcast.insert({ "_id": 2, "text": "In this release:                             " });
db.broadcast.insert({ "_id": 3, "text": "  Per-shell Versions feature                 " });
db.broadcast.insert({ "_id": 4, "text": "  documented in issue 52 & 82 on GitHub:     " });
db.broadcast.insert({ "_id": 5, "text": "  http://bit.ly/UcxBVb  http://bit.ly/12fAZRx" });
db.broadcast.insert({ "_id": 6, "text": "                                             " });
db.broadcast.insert({ "_id": 7, "text": "  Thanks to @pledbrook for this contribution." });
db.broadcast.insert({ "_id": 8, "text": "                                             " });
db.broadcast.insert({ "_id": 9, "text": "As always, please report any issues at:      " });
db.broadcast.insert({ "_id": 10,"text": "  https://github.com/gvmtool/gvm/issues      " });
