db.broadcast.remove();
db.broadcast.insert({ "_id": 1, "text": "GVM version 0.9.1                            " });
db.broadcast.insert({ "_id": 2, "text": "In this release:                             " });
db.broadcast.insert({ "_id": 3, "text": " * Many compatibility fixes for ZSH          " });
db.broadcast.insert({ "_id": 4, "text": " * Defaults to isolated mode enabled         " });
db.broadcast.insert({ "_id": 5, "text": " * Sourcing of files in ext folder           " });
db.broadcast.insert({ "_id": 6, "text": " * Cukes for the Isolated Shells feature     " });
db.broadcast.insert({ "_id": 7, "text": "                                             " });
db.broadcast.insert({ "_id": 8, "text": "Report any issues at:                        " });
db.broadcast.insert({ "_id": 9, "text": "  https://github.com/gvmtool/gvm/issues      " });
