#!/bin/bash
GRAILS_CMD=$1
if [ ! "$GVM_DIR" ]; then
    GVM_DIR="$HOME/.gvm"
fi
shift
#Look for the grails root directory
while [ ! -f 'application.properties' -a ! "`pwd`" == '/' ]; do
    cd ..
done

#If application properteis is found, use the specified version
if [ -f application.properties ]; then
    GRAILS_VERSION=`grep app.grails.version application.properties | sed -E 's/.*=(.*)/\1/'`
    echo "application.properties found, grails $GRAILS_VERSION"
    gvm use grails $GRAILS_VERSION
else 
    #If no applicaiton.properties is found, use the current version from GVM
	CURRENT=$(readlink "$GVM_DIR/grails/current" | sed -e "s_$GVM_DIR/grails/__g")
    echo "application.properties NOT found, using grails $CURRENT"
fi

$HOME/.gvm/grails/current/bin/$GRAILS_CMD $*
