name: Notify Chloé (Issue Triage)

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  notify:
    uses: sdkman/.github/.github/workflows/reusable-triage.yml@main
    secrets: inherit
