name: "Triage: Issues, Comments, PRs"
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
jobs:
  notify:
    uses: sdkman/.github/.github/workflows/reusable-triage-events.yml@main
    secrets: inherit
