name: Notify on Failure

on:
  workflow_run:
    workflows: ["*"]
    branches: [master, main]
    types: [completed]

jobs:
  notify:
    uses: sdkman/.github/.github/workflows/reusable-notify-on-failure.yml@main
    secrets: inherit
